setwd("E:/College Projects (Sem 3)/ML")
getwd()

df1<-read.table(file = "German-Credit_1.csv",header=T, sep = ",")
head(df1)
df1<-read.csv(file = "German-Credit_1.csv",header = T)


library(XLConnect)
library(rJava)
readLines(con = "German-Credit_1.csv", n = 5)
df2<-read.csv(file="German-Credit_2.csv", header = T)
head(df2)
df3<-merge(x=df1,y=df2,by="OBS",all = T)
head(df3)
summary(df3)
str(df3)
num_Attr<-c("DURATION","AMOUNT","INSTALL_RATE","AGE","NUM_CREDITS","NUM_DEPENDENTS")
cat_Attr<-setdiff(x=colnames(df3),y=num_Attr)
df3$OBS<-as.character(df3$OBS)
df3$RESPONSE<-as.factor(as.character(df3$RESPONSE))
df_cat<-subset(df3,select = cat_Attr)
df3[,cat_Attr]<-data.frame(apply(df_cat,2,function(x) as.factor(as.character(x))))
str(df3)
colSums(is.na(x=df3))
sum(is.na(df3))
df4<-na.omit(df3)
dim(df3)
dim(df4)
sum(is.na(df4))
library(DMwR)
install.packages("DMwR")
manyNAs(df3,0.1)
df3_imputed<-centralImputation(data = df3)
df3_imputed
sum(is.na(df3_imputed))

df3_imputed<-knnImputation(data=df3,k=5)
sum(is.na(df3_imputed))
install.packages("infotheo")
library(infotheo)
x<-c(5,6,7,8,8,8,8,8,11,20,21,22)
x0<-discretize(x,disc = "equalfreq",nbins=4)
table(x0)
x1<- discretize(x,disc = "equalwidth",nbins = 4)
table(x1)
install.packages("dummies")
library(dummies)
df_ex<-datasets::warpbreaks
table(df_ex$tension)
install.packages("vegan")
library(vegan)
